baseURL = "http://139.59.37.116/madhusthali/"
languageCode = "en-us"
theme = "slicedmango-school"
title = "Madhusthali Vidyapeeth"
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 9
[[menu.footer]]
name = "Gallery"
url = "/gallery/"
weight = 8
[[menu.footer]]
name = "Lifestyle"
url = "/about/"
weight = 7
[[menu.footer]]
name = "Academics"
url = "/academics/"
weight = 4
[[menu.footer]]
name = "The Group"
url = "/group/"
weight = 3
[[menu.footer]]
name = "About"
url = "/about/"
weight = 2
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 8
[[menu.main]]
name = "Gallery"
url = "/gallery/"
weight = 7
[[menu.main]]
name = "Lifestyle"
url = "/lifestyle/"
weight = 4
[[menu.main]]
name = "Academics"
url = "/academics/"
weight = 2
[[menu.main]]
name = "The Group"
url = "/group/"
weight = 3
[[menu.main]]
name = "Facilities"
url = "/facilities/"
weight = 6
[[menu.main]]
name = "Admission"
url = "/group/"
weight = 5
[params]
banner = "/images/default_banner.jpg"
logo = "/images/logo.png"
